// SCHREIER-SIMS - a strong generating set (a stabiliser chain) for the permutation group generated
// by the given permutations of {0..n-1}. Gives |G| exactly, membership testing in O(n^2), and an
// explicit word in the generators for any member. Permutations are 0-indexed images: p[i] is where
// i goes, and mul(a, b) means "apply a, THEN b", so (a*b)[i] = b[a[i]]. Level i of the chain holds
// coset representatives of the pointwise stabiliser of 0..i-1, indexed by the image of i, so
// |G| = product of the transversal sizes and every element factors uniquely as one rep per level.
// WHEN: "you may apply these shuffles to the array any number of times, in any order - how many
// distinct arrangements are reachable, and is arrangement X reachable". Model a shuffle as the
// permutation it applies, then the reachable arrangements are exactly the group elements: order()
// counts them and has() decides reachability. word() prints the moves that get you there. Also:
// the group generated by a puzzle's legal moves, the size of a symmetry group before a Burnside
// count, and "do these generators generate all of S_n" (compare order() with n!).
// CONVENTION TRAP: an arrangement is the permutation taking the START to it, so ask has(q) with
// q[i] = the index the item now at position i started at (build it once, consistently, then stay
// consistent). If the array has DUPLICATE values, the number of distinct arrangements is |G| over
// the size of the stabiliser of that multiset, NOT |G| - this file does not give you that.
// COMPLEXITY: level i holds at most n - i reps, so O(n^2) stored permutations and O(n^3) ints of
// memory (under 1 MB even at n = 60). The constructor sifts every rep at level i against every rep
// at a level >= i: O(n^4) sifts costing O(n^2) each, so O(n^6) when the group is all of S_n.
// MEASURED on three random generators of S_n: n = 40 takes 0.5 s, n = 50 takes 2 s, n = 60 takes
// 6 s, and that is the wall - past it you need a real Schreier-Sims (Schreier generators kept per
// level, plus Jerrum's filter) or the randomised variant. has() and word() are O(n^2) per query.
// DEGENERATE: no generators or only identities gives order() == 1 and has(id) == true; n = 1 the
// same. Duplicate generators are free. word(identity) is the empty word.
// EXACT: integers only. OVERFLOW: |G| <= n! exceeds ll at n = 21 (20! = 2.4e18 fits), so switch
// order() to __int128 (good to 33!) or accumulate modulo the answer's modulus for larger n.
struct PermGroup {
    int n; bool keepW;
    vector<vi> lk;                                    // lk[i][j] = index of the level i rep i->j
    vector<vector<vi>> T, Ti, W;                      // reps, their inverses, and their words
    static vi mul(const vi& a, const vi& b) {
        vi c(sz(a));
        for (int i = 0; i < sz(a); i++) c[i] = b[a[i]];
        return c;
    }
    static vi inv(const vi& a) {
        vi c(sz(a));
        for (int i = 0; i < sz(a); i++) c[a[i]] = i;
        return c;
    }
    // Strip p through the chain. Returns the level where p is NEW (and inserts it there if add),
    // or -1 when p reduces to the identity, i.e. p is in the group. w accumulates the word of the
    // running residue, so it ends as the word of p^-1 when p sifts through.
    int sift(vi p, vi& w, bool add) {
        for (int i = 0; i < n; i++) {
            int k = lk[i][p[i]];
            if (k < 0) {
                if (!add) return i;
                lk[i][p[i]] = sz(T[i]), T[i].pb(p), Ti[i].pb(inv(p));
                if (keepW) W[i].pb(w);
                return i;
            }
            if (keepW) for (int j = sz(W[i][k]) - 1; j >= 0; j--) w.pb(~W[i][k][j]);  // w *= rep^-1
            bool one = true;                          // p *= rep^-1 in place; now p fixes 0..i, so
            for (int j = i; j < n; j++)               // only j >= i can move and only they matter
                one &= (p[j] = Ti[i][k][p[j]]) == j;
            if (one) return -1;                       // already the identity: skip the rest
        }
        return -1;
    }
    PermGroup(int n, const vector<vi>& gen, bool keepW = false) : n(n), keepW(keepW) {
        lk.assign(n, vi(n, -1)), T.resize(n), Ti.resize(n), W.resize(n);
        vi id(n);
        iota(all(id), 0);
        for (int i = 0; i < n; i++) lk[i][i] = 0, T[i].pb(id), Ti[i].pb(id), W[i].pb(vi());
        vector<pii> el;                               // every non-identity rep, as (level, index)
        auto push = [&](vi p, vi w) {
            int i = sift(p, w, true);
            if (i >= 0) el.pb({i, sz(T[i]) - 1});
        };
        for (int g = 0; g < sz(gen); g++) push(gen[g], vi{g});
        for (int i = 0; i < sz(el); i++) for (int j = 0; j <= i; j++) {   // el grows as we go
            auto prod = [&](pii a, pii b) {
                vi w;
                if (keepW) w = W[a.fi][a.se], w.insert(w.end(), all(W[b.fi][b.se]));
                push(mul(T[a.fi][a.se], T[b.fi][b.se]), w);
            };
            if (el[i].fi <= el[j].fi) prod(el[i], el[j]);       // a level i rep times a
            if (el[j].fi <= el[i].fi && i != j) prod(el[j], el[i]);   // level >= i element is
                                                                      // a Schreier generator
        }
    }
    ll order() {
        ll r = 1;
        for (int i = 0; i < n; i++) r *= sz(T[i]);
        return r;
    }
    bool has(vi p) { vi w; return sift(p, w, false) < 0; }
    vi word(vi p) {                                   // PRECONDITION: has(p), and keepW was set.
        vi w;                                         // token g >= 0 is gen[g], ~g is its inverse
        sift(p, w, false);
        reverse(all(w));
        for (int& x : w) x = ~x;                      // w held p^-1; invert it
        return w;
    }
};
// Rebuild p from word(p) with res = mul(res, x >= 0 ? gen[x] : inv(gen[~x])) over the tokens in
// order. Word LENGTH IS NOT BOUNDED - it is a product of stored words and can blow up; use it only
// where the checker accepts any move sequence. If you need short words, use only for small groups.
// ORBIT of one point (which positions a single item can reach) is a plain BFS on the generators
// in O(n t) - do not build the whole chain for that. The level-0 transversal IS the orbit of 0.
// The pointwise stabiliser of 0..i-1 is generated by the reps at levels >= i, which is how you
// answer "how many arrangements fix these positions" (= product of |T[j]| for j >= i).
// Related: Burnside / Polya for counting colourings up to the group, and the parity argument that
// solves the 15-puzzle style problems in one line when the group is the full alternating group.
