// Needs: powmod, factorize (02 - Primes and Divisors/06 - MillerRabinPollard.cpp),
//        discreteLog (02 - DiscreteLogAndRoots.cpp), CRT (01 - CRT.cpp).
// POHLIG-HELLMAN DISCRETE LOG - solve g^x = h (mod p) in O(sum over q^e || n of e*(log n + sqrt q))
// instead of the O(sqrt p) of plain baby-step giant-step, where n = ord(g). It is a massive win
// exactly when n is SMOOTH (all prime factors small), which is common in constructed problems:
// p - 1 = 2^k * small stuff, or a subgroup of small order.
// THE IDEA: the discrete log is determined modulo each prime power q^e dividing n. Inside the
// order-q subgroup a log costs only O(sqrt q), and the q-adic digits of x are recovered one at a
// time; CRT glues the residues back together.
// PRECONDITIONS: p PRIME (the inverse below uses Fermat), g of multiplicative order exactly n
// (pass n = p - 1 when g is a primitive root), 0 < h < p. Returns x in [0, n), or -1 if h is not
// in the subgroup generated by g.
ll pohligHellman(ll g, ll h, ll p, ll n) {
    vector<ll> rs, ms;
    for (auto [q, e] : factorize(n)) {
        ll qe = 1;
        for (int i = 0; i < e; i++) qe *= q;
        ll gq = powmod(g, n / q, p), x = 0, cur = 1;    // gq generates the subgroup of order q
        for (int k = 0; k < e; k++) {                   // recover the q-adic digits of x
            ll gx = powmod(powmod(g, x, p), p - 2, p);  // g^-x
            ll hk = powmod((ll)((__int128)h * gx % p), n / (cur * q), p);
            ll d = discreteLog(gq, hk, p);              // a log inside a group of size q
            if (d < 0) return -1;
            x += d * cur, cur *= q;
        }
        rs.push_back(x % qe), ms.push_back(qe);
    }
    return CRT(rs, ms).first;
}
// WHEN TO USE WHICH
//   n smooth              -> this file (can be near-instant even for p ~ 1e18)
//   n has a large prime   -> plain BSGS, O(sqrt p) time AND memory (02 - DiscreteLogAndRoots.cpp)
//   composite modulus     -> the BSGS in 02 already strips gcd(a, m); Pohlig-Hellman needs a
//                            group, so factor m and CRT the per-prime-power answers yourself.
// SANITY: check powmod(g, n, p) == 1 and that n really is the ORDER of g (multOrder), otherwise
// the CRT reassembles a residue modulo the wrong number and the answer is silently wrong.
// SECURITY TRIVIA THAT IS ACTUALLY A HINT: this is why cryptographic primes are chosen so that
// p - 1 has a large prime factor. If a problem hands you a "random" prime whose p - 1 factors
// into small pieces, that is the intended solution.
