// Needs: extGCD (01 - ExtendedEuclid.cpp).
// A SYSTEM OF TWO LINEAR DIOPHANTINE EQUATIONS IN ANY NUMBER OF UNKNOWNS:
//   sum x_i * a_i = p   and   sum x_i * b_i = q,   x_i ANY integers - is it solvable?
// Equivalently: is (p, q) in the subgroup of Z^2 generated by the vectors (a_i, b_i)? Keep that
// lattice in Hermite normal form as two vectors (g, s) and (0, t): every lattice point is
// m*(g, s) + k*(0, t), with g >= 0, t >= 0 and 0 <= s < t when t > 0. Adding a generator is one
// extended-gcd step, so this is ONLINE - generators may arrive interleaved with queries, which
// is what makes it more than "solve a 2 x N system once".
// add() is O(log), contains() is O(1). No preconditions; zero vectors and rank 0/1 are handled.
// OVERFLOW: add() forms s*(c/g) and d*(g/g'), so keep coordinates below ~2e9 or switch to __int128.
struct Lattice2D {
    ll g = 0, s = 0, t = 0;                             // t = 0 means "no free second direction"
    void add(ll c, ll d) {                              // insert the generator (c, d)
        if (c < 0) c = -c, d = -d;                      // (c, d) and its negative are equivalent
        if (c == 0) {                                   // pure vertical generator
            t = gcd(t, d < 0 ? -d : d);
            if (t) s = ((s % t) + t) % t;
            return;
        }
        if (g == 0) { g = c, s = t ? ((d % t) + t) % t : d; return; }
        ll x, y, ng = extGCD(g, c, x, y);               // ng = gcd(g, c) = g*x + c*y
        ll cross = s * (c / ng) - d * (g / ng);         // the leftover pure-vertical direction
        t = gcd(t, cross < 0 ? -cross : cross);
        ll ns = s * x + d * y;
        g = ng, s = t ? ((ns % t) + t) % t : ns;
    }
    bool contains(ll p, ll q) {                         // is (p, q) representable?
        if (g == 0) return p == 0 && (t ? q % t == 0 : q == 0);
        if (p % g) return false;
        ll rem = q - (p / g) * s;
        return t ? rem % t == 0 : rem == 0;
    }
};
// WHY IT WORKS: extGCD writes (ng, ns) = x*(g, s) + y*(c, d) with ng = gcd(g, c), the smallest
// positive first coordinate achievable. What remains is the sublattice with first coordinate 0,
// generated by s*(c/ng) - d*(g/ng) - the determinant of the two old generators divided by ng.
// THE SAME OBJECT in higher dimension is the Hermite normal form of the generator matrix; with
// one row it degenerates to gcd, and 02 - LinearDiophantine.cpp is the single-equation version.
// TYPICAL USES: "can I reach (p, q) using these moves any integer number of times", reachability
// with two conserved quantities, and answering many (p, q) queries against a growing move set.
// NOTE this allows NEGATIVE x_i. Requiring x_i >= 0 is a completely different (much harder)
// problem - see 08 - CoinReachability.cpp for the one-equation nonnegative version.
